services:
    daiku.web:
        build:
            context: application/vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/daiku
        container_name: daiku_web
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './application:/var/www/html'
        networks:
            - daiku_net
        depends_on:
            - daiku.db
            # - redis
            # - meilisearch
            # - mailpit
            # - selenium
    daiku.db:
        image: postgres:16.2-alpine3.19
        container_name: daiku_db
        environment:
        - POSTGRES_LOGGING=true
        - POSTGRES_DB=daiku
        - POSTGRES_PASSWORD=ASLJ023470AlserLFH
        - POSTGRES_USER=daiku
        - POSTGRES_POSTGRES_PASSWORD=alj2340aaALJAF2341408AUUZLJK
        - "ES_JAVA_OPTS=-Xms1024m -Xmx3072m"
        ports:
        - "5436:5432"
        healthcheck:
            test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
            interval: 10s
            timeout: 2s
            retries: 10
        volumes:
            - type: volume
              source: daiku_db
              target: /var/lib/postgresql/data
              volume:
                nocopy: true
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        networks:
        - daiku_net
    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'sail-redis:/data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - redis-cli
    #             - ping
    #         retries: 3
    #         timeout: 5s
    # meilisearch:
    #     image: 'getmeili/meilisearch:latest'
    #     ports:
    #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #     environment:
    #         MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    #     volumes:
    #         - 'sail-meilisearch:/meili_data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - wget
    #             - '--no-verbose'
    #             - '--spider'
    #             - 'http://localhost:7700/health'
    #         retries: 3
    #         timeout: 5s
    # mailpit:
    #     image: 'axllent/mailpit:latest'
    #     ports:
    #         - '${FORWARD_MAILPIT_PORT:-1025}:1025'
    #         - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    #     networks:
    #         - sail
    #  selenium:
    #     image: seleniarm/standalone-chromium
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
networks:
    daiku_net:
        driver: bridge
volumes:
    daiku_db:
        driver: local
    # sail-redis:
    #     driver: local
    # sail-meilisearch:
    #     driver: local
